import { Meteor } from 'meteor/meteor';
import '../imports/api/collections/ContactsCollection';
import '../imports/api/methods/ContactsMethods';
import '../imports/api/publications/ContactsPublications';
import '../imports/api/collections/WalletsCollection';
import '../imports/api/collections/TransactionsCollection';
import '../imports/api/methods/TransactionsMethods';
import '../imports/api/publications/WalletsPublications';
import '../infra/CustomError';
import '../infra/accounts';
import '../infra/roles';
import '../imports/api/methods/RolesMethods';